
$pdf_mode = 1;
$xelatex = "xelatex -synctex=1 --shell-escape -interaction=nonstopmode %O %S";
$pdflatex = "xelatex -synctex=1 --shell-escape -interaction=nonstopmode %O %S";
$biber = "biber --validate-datamodel %O %S";
$preview_mode = 1;
$cleanup_mode = 2;

add_cus_dep('glo', 'gls', 0, 'run_makeglossaries');
add_cus_dep('acn', 'acr', 0, 'run_makeglossaries');

sub run_makeglossaries {
  my $base = $_[0];
  my $q = $silent ? "-q" : "";
  if ($out_dir && $base =~ /^\Q$out_dir\E\/(.*)/) {
    system "cd \"$out_dir\" && makeglossaries $q \"$1\"";
  } else {
    system "makeglossaries $q \"$base\"";
  }
}

push @generated_exts, 'glo', 'gls', 'glg';
push @generated_exts, 'acn', 'acr', 'alg';
push @generated_exts, 'synctex.gz';

$clean_ext = 'acn acr alg aux bbl bcf blg brf fdb_latexmk glg glo gls idx ilg ind ist lof log lot out run.xml toc toe dvi slg slo sls xdy listing'